CREATE TABLE ABSENTS (ABSENT_ID INT PRIMARY KEY, EMPLOYEE_ID INT NOT NULL, TOTAL_LEAVES INT DEFAULT 0, ANNUAL_LEAVES INT DEFAULT 0, SICK_LEAVES INT DEFAULT 0, FLEXI_LEAVES INT DEFAULT 0);

CREATE TABLE ABSENCES_DETAILS (ABSENCES_DETAILS_ID INT PRIMARY KEY, ABSENT_ID INT REFERENCES ABSENTS(ABSENT_ID),  ABSENT_TYPE varchar(50) NOT NULL, DAYS INT DEFAULT 0, PROJECT_CODE INT NOT NULL, FROM_DATE DATE NOT NULL, TO_DATE DATE NOT NULL, APPROVAL_STATUS BOOLEAN DEFAULT FALSE);
